Remove required status when updating order
Method `OrdersRepository::update()` checks if status of order was
changed by update. If it was, event is emitted.

But status itself is not required for order update - so it should be
required.

Fixes error:

  ErrorException: Undefined array key "status"
  in products-module/src/Models/Repository/OrdersRepository.php:92

remp/crm#2880